version: '3'

services:
  redis:
    restart: always
    image: redis:6.2
    ports:
      - "6379:6379"
  
  django:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    container_name: poker_service
    volumes:
      - .:/poker_service
    ports:
      - "8000:8000"
    depends_on:
      - redis
